.PHONY: generate test testrace

generate:
	go generate ./...

lint: generate
	go fmt ./...
	go vet ./...
	go run golang.org/x/lint/golint -set_exit_status ./...
	go run honnef.co/go/tools/cmd/staticcheck -checks all ./...

test: generate
	go test -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...

testrace: generate
	go test -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...


